name: Main

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    environment: github-pages
    env:
      VITE_HONEYBADGER_API_KEY: 5a243a081e0d1b2cc860a1bd192d3eb972cbd2b20a236599c3f3dac4d8a79fd4
      VITE_POSTHOG_API_KEY: phc_OvLeJMxcLVrD8JhVe0sYkgh20VvBeHQGHtiYG7Daprh
      VITE_AUTH_TENANT_URL: https://zbn.webhook.store

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn
      - run: yarn predeploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
      - uses: honeybadger-io/github-notify-deploy-action@v1
        with:
          api_key: ${{ secrets.HONEYBADGER_API_KEY }}